# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ec482cc359750c74aa05c6cb12354274469edc7cfa8bfec760af3a39e42611a836380204f055fee442dcefb289e289ae12e9c9f899928599e409ff04b4a585c

test:
  secret_key_base: a8cb23f8203f1f26e2129a02b474504052c11deb73d9dcddbfe1695b49e4c91e7dce4844217d3803e0b6a79279cbaae4137c4b760f55a5f718a079548ba0e357

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
